apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ebooks-tasksui
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ebooks
        tier: tasksui
    spec:
      containers:
      - name: rero-ebooks
        image: rero/rero-ebooks:latest
        command: ["celery", "-A", "invenio_app", "flower"]
        imagePullPolicy: Always
        env:
        - name: PATH
          value: /usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/ebooks/ebooks/bin
        - name: GET_HOSTS_FROM
          value: dns
        - name: RABBITMQ_DEFAULT_USER
          valueFrom:
            secretKeyRef:
              name: rero-ebooks
              key: worker-user
        - name: RABBITMQ_DEFAULT_PASS
          valueFrom:
            secretKeyRef:
              name: rero-ebooks
              key: worker-password
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: rero-ebooks
              key: db-user
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: rero-ebooks
              key: db-name
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rero-ebooks
              key: db-password
        - name: INVENIO_APP_ENABLE_SECURE_HEADERS
          value: 'False'
        - name: INVENIO_APP_ALLOWED_HOSTS
          value: None
        - name: INVENIO_SEARCH_ELASTIC_HOSTS
          value: ebooks-indexer:$(EBOOKS_INDEXER_SERVICE_PORT_API)
        - name: INVENIO_SQLALCHEMY_DATABASE_URI
          value: postgresql+psycopg2://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@ebooks-db:$(EBOOKS_DB_SERVICE_PORT_DB)/$(POSTGRES_DB)
        - name: INVENIO_CELERY_BROKER_URL
          value: 'amqp://$(RABBITMQ_DEFAULT_USER):$(RABBITMQ_DEFAULT_PASS)@ebooks-worker:$(EBOOKS_WORKER_SERVICE_PORT_WORKER)//'
        - name: INVENIO_CELERY_RESULT_BACKEND
          value: 'redis://ebooks-cache:$(EBOOKS_CACHE_SERVICE_PORT_CACHE)/1'
        - name: INVENIO_CACHE_REDIS_URL
          value: 'redis://ebooks-cache:$(EBOOKS_CACHE_SERVICE_PORT_CACHE)/1'
        - name: INVENIO_RATELIMIT_STORAGE_URL
          value: 'redis://ebooks-cache:$(EBOOKS_CACHE_SERVICE_PORT_CACHE)/3'
        - name: INVENIO_ACCOUNTS_SESSION_REDIS_URL
          value: 'redis://ebooks-cache:$(EBOOKS_CACHE_SERVICE_PORT_CACHE)/0'
        - name: INVENIO_DB_VERSIONING
          value: '0'
        - name: INVENIO_MAIL_SUPPRESS_SEND
          value: '0'
        - name: INVENIO_MAIL_SERVER
          valueFrom:
            secretKeyRef:
              name: rero-ebooks
              key: mail-server
        - name: INVENIO_SECURITY_EMAIL_SENDER
          valueFrom:
            secretKeyRef:
              name: rero-ebooks
              key: mail-sender
        - name: INVENIO_JSONSCHEMAS_HOST
          value: ebooks.test.rero.ch
        - name: INVENIO_OAISERVER_ID_PREFIX
          value: 'oai:ebooks.test.rero.ch:'
        - name: INVENIO_OAISERVER_PAGE_SIZE
          value: '500'
        ports:
        - containerPort: 5555
        volumeMounts:
          - mountPath: /data
            name: ebooks-data
      volumes:
      - name: ebooks-data
        hostPath:
          path: /data/docker/ebooks
